version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "igorlombacx"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - "igorlombacx"
