name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  tag-creation:
    name: Create Release Tag
    permissions:
      contents: write  # for Git to git push
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Tag
        env:
          TAG: ${{ github.event.inputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${TAG}"
          echo "NEXT_VERSION=${TAG}" >> $GITHUB_ENV
          message="${TAG}: Manual tag creation"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git tag -a "${TAG}" -m "${message}"
          git push origin "${TAG}"
