name: PR Automation
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [ready_for_review, opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: none  # no access to repository contents

jobs:
  add-reviewers:
    name: Request reviewers
    permissions:
      issues: write  # for adding reviewers as comments
      pull-requests: write  # for pr edit command
    runs-on: cx-public-ubuntu-x64
    if: ${{ github.event.pull_request.user.type != 'Bot' }}
    steps:
      - name: Request reviewers
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          PRNUM: ${{ github.event.pull_request.number }}
          PRAUTHOR: ${{ github.event.pull_request.user.login }}
        run: gh pr edit $PRNUM --add-reviewer cx-anurag-dalke
